# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hand_pb2 as hand__pb2


class HandProcessorStub(object):
    """سرویسی که مختصات را دریافت می‌کند
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPosition = channel.unary_unary(
                '/hand_service.HandProcessor/SendPosition',
                request_serializer=hand__pb2.PositionRequest.SerializeToString,
                response_deserializer=hand__pb2.EmptyResponse.FromString,
                )


class HandProcessorServicer(object):
    """سرویسی که مختصات را دریافت می‌کند
    """

    def SendPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPosition,
                    request_deserializer=hand__pb2.PositionRequest.FromString,
                    response_serializer=hand__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hand_service.HandProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandProcessor(object):
    """سرویسی که مختصات را دریافت می‌کند
    """

    @staticmethod
    def SendPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hand_service.HandProcessor/SendPosition',
            hand__pb2.PositionRequest.SerializeToString,
            hand__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
