# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hand.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhand.proto\x12\x0chand_service\"\'\n\x0fPositionRequest\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x0f\n\rEmptyResponse2]\n\rHandProcessor\x12L\n\x0cSendPosition\x12\x1d.hand_service.PositionRequest\x1a\x1b.hand_service.EmptyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hand_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITIONREQUEST']._serialized_start=28
  _globals['_POSITIONREQUEST']._serialized_end=67
  _globals['_EMPTYRESPONSE']._serialized_start=69
  _globals['_EMPTYRESPONSE']._serialized_end=84
  _globals['_HANDPROCESSOR']._serialized_start=86
  _globals['_HANDPROCESSOR']._serialized_end=179
# @@protoc_insertion_point(module_scope)
